export const OBJECT_METADATA = {
  STATIC_OBJECTS: {
    defaultObject: {
      thumbnail: "/images/domino.png",
      model: "defaultObject",
      sound: "/sounds/domino_drop.mp3",
      colliders: "cuboid",
      type: "dynamic",
      title: "도미노",
    },
    spiralStairs: {
      thumbnail: "/images/spiral_stairs.png",
      model: "/objects/spiral_stairs.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      type: "dynamic",
      title: "회전 트랙",
    },
    slide: {
      thumbnail: "/images/slide.png",
      model: "/objects/slide.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      type: "dynamic",
      title: "미끄럼틀",
    },
    stairsClosedShort: {
      thumbnail: "/images/stairs_closed_short.png",
      model: "/objects/stairs_closed_short.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      type: "dynamic",
      title: "계단",
    },
    lightbulb: {
      thumbnail: "/images/lightbulb.png",
      model: "/objects/lightbulb.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      type: "fixed",
      title: "전구",
    },
    bumper: {
      thumbnail: "/images/bumper.png",
      model: "/objects/bumper.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      title: "범퍼",
    },
  },
  DYNAMIC_OBJECTS: {
    steelBall: {
      thumbnail: "/images/beach_ball.png",
      model: "/objects/steel_ball.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "hull",
      type: "dynamic",
      title: "쇠구슬",
    },
    beachBall: {
      thumbnail: "/images/beach_ball.png",
      model: "/objects/beach_ball.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "hull",
      type: "dynamic",
      title: "비치볼",
    },
    soccerFootball: {
      thumbnail: "/images/soccer_football.png",
      model: "/objects/soccer_football.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "hull",
      type: "dynamic",
      title: "축구공",
    },
    cannon: {
      thumbnail: "/images/cannon.png",
      model: "/objects/cannon.glb",
      sound: "/sounds/domino_drop.mp3",
      type: "fixed",
      title: "대포",
    },
    car: {
      thumbnail: "/images/car.png",
      model: "/objects/car.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      title: "자동차",
    },
  },
};

export const OBJECT_GROUP_LABELS = {
  STATIC_OBJECTS: "Static Object",
  DYNAMIC_OBJECTS: "Dynamic Object",
};
