export const OBJECT_PATHS = {
  STATIC_OBJECTS: {
    defaultObject: {
      thumbnail: "/images/domino.png",
      model: "defaultObject",
      sound: "/sounds/domino_drop.mp3",
      colliders: "cuboid",
      name: "domino",
    },
    slide: {
      thumbnail: "/images/slide.png",
      model: "/objects/slide.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      name: "slide",
    },
    spiralStairs: {
      thumbnail: "/images/spiral_stairs.png",
      model: "/objects/spiral_stairs.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      name: "spiralStairs",
    },
    staircase: {
      thumbnail: "/images/staircase.png",
      model: "/objects/staircase.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      name: "staircase",
    },
    stairsClosedShort: {
      thumbnail: "/images/stairs_closed_short.png",
      model: "/objects/stairs_closed_short.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      name: "stairsClosedShort",
    },
    stairsClosed: {
      thumbnail: "/images/stairs_closed.png",
      model: "/objects/stairs_closed.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      name: "stairsClosed",
    },
    stairs: {
      thumbnail: "/images/stairs.png",
      model: "/objects/stairs.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      name: "stairs",
    },
    lightbulb: {
      thumbnail: "/images/lightbulb.png",
      model: "/objects/lightbulb.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "trimesh",
      name: "lightbulb",
    },
  },
  DYNAMIC_OBJECTS: {
    beachBall: {
      thumbnail: "/images/beach_ball.png",
      model: "/objects/beach_ball.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "ball",
      name: "beachBall",
    },
    cannon: {
      thumbnail: "/images/cannon.png",
      model: "/objects/cannon.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "hull",
      name: "cannon",
    },
    pokeball: {
      thumbnail: "/images/pokeball.png",
      model: "/objects/pokeball.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "ball",
      name: "pokeball",
    },
    soccerFootball: {
      thumbnail: "/images/soccer_football.png",
      model: "/objects/soccer_football.glb",
      sound: "/sounds/domino_drop.mp3",
      colliders: "ball",
      name: "soccerFootball",
    },
  },
};
